name: qadaa
description: A new Flutter project.

publish_to: "none"

version: 1.5.1+7

environment:
  # sdk: ">=2.18.5 <3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^6.1.0
  awesome_notifications: ^0.9.3+1
  confetti: ^0.7.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screen_lock: ^9.1.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  rxdart: ^0.28.0
  sleek_circular_slider: ^2.0.1
  url_launcher: ^6.3.0
  wakelock_plus: ^1.2.8
  window_manager: ^0.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#303030"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

flutter_intl:
  enabled: true
